### ISSUE TITLE
A new home for this project? 😄 

### ISSUE THREAD

**Issue by leerob** [vercel-community/vercel-rust#43]
Hey Mike! First off, thank you for taking over with this project and providing an option for users wanting to build functions with Rust on Vercel. We really, really appreciate all of your work. I know that you're now looking for maintainers, and we're going to be putting more effort behind Rust support on Vercel.

We're started to create a Vercel Community GitHub organization, where we'll support community runtimes like Rust and friends. I've started the process of migrating this repo over to the community (https://github.com/vercel-community/rust)

Before proceeding further, I just wanted to check in with you and make sure this was okay. I've credited you in the repo 🙏 and would be happy to talk about next steps if you're okay with this!

**Comment by mike-engel** [comment]
Hi @leerob, thanks for the message and the update. I unfortunately haven't used vercel much in a while, nor rust, nor this project, so maintaining it has become a bit of a burden. With that said, I'm happy to transfer it over to vercel and the community, who will keep it much more up to date than I.

When it's been fully transferred, let me know and I'll archive this repo. Additionally, if there's anything I can do to help, let me know.

**Comment by leerob** [comment]
@mike-engel I sent you an invite to the org, where you'll be able to transfer it! I can't initiate it from my side unless you make me an admin here.

**Comment by mike-engel** [comment]
@leerob just to be clear, you'd like me to transfer this repo over to the `vercel-community` org? Apologies for the slow reply—currently on holiday. I was under the impression that you were copying everything manually into a new repo. Will that one be living side-by-side with `vercel-rust` after the transfer? I'm not clear on that.

Thanks!

**Comment by leerob** [comment]
@mike-engel Ideally we can transfer this repo over - I'll move the changes from the new repo back to here. This can preserve git history and also keep the deployment pipeline that's set up for publishing! Could you also give me NPM permissions for publishing then, as well? Thank you! Username: leerobinson

**Comment by mike-engel** [comment]
@leerob got it, thanks! Transferred over, and I've added you as a writer to the npm package.
